// Destinations on the globe. Budgets are a rough guide per person per day in rupees, excluding flights.

export const TAGS = [
  ["all", "Everywhere"],
  ["beach", "Beaches"],
  ["mountains", "Mountains"],
  ["culture", "Culture"],
  ["food", "Food"],
  ["adventure", "Adventure"],
];

export const DESTINATIONS = [
  {
    id: "goa",
    name: "Goa",
    country: "India",
    lat: 15.3,
    lon: 74.08,
    tags: ["beach", "food"],
    best: [11, 12, 1, 2],
    days: 4,
    perDay: 4000,
    blurb: "Lazy beaches in the south, beach shacks and night markets in the north, and Portuguese-era churches and spice farms in between.",
  },
  {
    id: "kerala",
    name: "Kerala backwaters",
    country: "India",
    lat: 9.5,
    lon: 76.34,
    tags: ["food", "culture"],
    best: [9, 10, 11, 12, 1, 2, 3],
    days: 3,
    perDay: 4500,
    blurb: "A night on a houseboat through palm-lined canals, appam and stew for breakfast, and a Kathakali performance in Kochi.",
  },
  {
    id: "ladakh",
    name: "Ladakh",
    country: "India",
    lat: 34.15,
    lon: 77.58,
    tags: ["mountains", "adventure"],
    best: [5, 6, 7, 8, 9],
    days: 7,
    perDay: 5000,
    blurb: "High passes, monasteries on cliffs and the impossible blue of Pangong lake. Give yourself two slow days to acclimatise.",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    country: "India",
    lat: 26.91,
    lon: 75.79,
    tags: ["culture", "food"],
    best: [10, 11, 12, 1, 2, 3],
    days: 3,
    perDay: 3500,
    blurb: "The pink old city, Amber fort at sunrise, block-printed textiles and a thali that does not stop coming.",
  },
  {
    id: "hampi",
    name: "Hampi",
    country: "India",
    lat: 15.34,
    lon: 76.46,
    tags: ["culture", "adventure"],
    best: [10, 11, 12, 1, 2],
    days: 2,
    perDay: 2500,
    blurb: "Ruins of the Vijayanagara empire scattered across a landscape of giant boulders. Rent a bicycle and watch sunset from Matanga hill.",
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    country: "India",
    lat: 11.97,
    lon: 92.99,
    tags: ["beach", "adventure"],
    best: [11, 12, 1, 2, 3, 4],
    days: 5,
    perDay: 6000,
    blurb: "Clear water and coral reefs off Havelock and Neil islands. Good for a first scuba dive or simply a hammock.",
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    lat: -8.41,
    lon: 115.19,
    tags: ["beach", "culture", "food"],
    best: [4, 5, 6, 7, 8, 9, 10],
    days: 6,
    perDay: 6500,
    blurb: "Rice terraces around Ubud, temple ceremonies, surf in the south and quieter beaches on the east coast.",
  },
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    lat: 35.01,
    lon: 135.77,
    tags: ["culture", "food"],
    best: [3, 4, 5, 10, 11],
    days: 4,
    perDay: 12000,
    blurb: "Temples and moss gardens, the torii tunnel at Fushimi Inari before the crowds, and kaiseki dinners in old townhouses.",
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    lat: 36.39,
    lon: 25.46,
    tags: ["beach", "food"],
    best: [5, 6, 9, 10],
    days: 3,
    perDay: 14000,
    blurb: "White villages on the rim of a flooded volcano, black-sand beaches and the famous sunset from Oia.",
  },
  {
    id: "cappadocia",
    name: "Cappadocia",
    country: "Türkiye",
    lat: 38.64,
    lon: 34.83,
    tags: ["adventure", "culture"],
    best: [4, 5, 6, 9, 10],
    days: 3,
    perDay: 9000,
    blurb: "Fairy chimneys, underground cities and a sky full of hot-air balloons at dawn.",
  },
  {
    id: "interlaken",
    name: "Swiss Alps",
    country: "Switzerland",
    lat: 46.69,
    lon: 7.86,
    tags: ["mountains", "adventure"],
    best: [6, 7, 8, 9, 12, 1, 2, 3],
    days: 4,
    perDay: 16000,
    blurb: "Lakes the colour of glass, cogwheel trains to glaciers, and paragliding over Interlaken in summer or skiing in winter.",
  },
  {
    id: "iceland",
    name: "Iceland",
    country: "Iceland",
    lat: 64.15,
    lon: -21.94,
    tags: ["adventure", "mountains"],
    best: [6, 7, 8, 9, 10, 2, 3],
    days: 7,
    perDay: 18000,
    blurb: "Waterfalls, black beaches and glaciers along the Ring Road; midnight sun in summer, northern lights from September.",
  },
  {
    id: "cusco",
    name: "Machu Picchu",
    country: "Peru",
    lat: -13.16,
    lon: -72.55,
    tags: ["adventure", "culture"],
    best: [5, 6, 7, 8, 9],
    days: 4,
    perDay: 9000,
    blurb: "The Inca citadel in the clouds, reached by train or a four-day trail, with Cusco's markets to start and finish.",
  },
  {
    id: "capetown",
    name: "Cape Town",
    country: "South Africa",
    lat: -33.92,
    lon: 18.42,
    tags: ["beach", "food", "mountains"],
    best: [11, 12, 1, 2, 3],
    days: 5,
    perDay: 9000,
    blurb: "Table Mountain above the city, penguins at Boulders Beach, the Cape Point drive and wine valleys an hour away.",
  },
  {
    id: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    lat: -45.03,
    lon: 168.66,
    tags: ["adventure", "mountains"],
    best: [12, 1, 2, 6, 7, 8],
    days: 5,
    perDay: 13000,
    blurb: "Bungee, jet boats and ski fields, plus a day trip to Milford Sound for fjords and waterfalls.",
  },
];
